from . import account_move
from . import helpdesk_category
from . import helpdesk_tag
from . import helpdesk_type
from . import mail_compose_message
from . import merge_ticket
from . import project_task
from . import res_config_settings
from . import support_ticket
from . import team_helpdesk
from . import ticket_helpdesk
from . import ticket_stage
from . import website_menu
from . import service_level_agreement
from . import ticket_status
