{
    'name': 'Hotel Management',
    'version': '18.0.1.0.0',
    'category': 'Industries',
    'summary': """A complete Hotel Management System that cover all areas of 
    Hotel services""" ,
    'description': """The module helps you to manage rooms, amenities, 
    services, food, events and vehicles. End Users can book rooms and reserve 
    foods from hotel.""",
    'author':'KoderXpert Technologies LLP',
    'company': 'KoderXpert Technologies LLP',
    'maintainer': 'KoderXpert Technologies LLP',
    'website': 'https://koderxpert.com',
    'depends': ['account', 'event', 'fleet', 'lunch', 'website'],
    'data': [
        'security/hotel_groups.xml',
        # 'security/hotel_security.xml',
        'security/ir.model.access.csv',
        'data/ir_data_sequence.xml',
        'views/room_booking_views.xml',
        'views/account_move_views.xml',
        'views/hotel_room_views.xml',
        'views/hotel_amenity_views.xml',
        'views/hotel_service_views.xml',
        'views/hotel_floor_views.xml',
        'views/lunch_product_views.xml',
        'views/fleet_vehicle_model_views.xml',
        'views/food_booking_line_views.xml',
        'views/dashboard_view.xml',
        # 'views/website_booking_form.xml',
        'views/web_room_template.xml',
        'wizard/room_booking_detail_views.xml',
        'wizard/sale_order_detail_views.xml',
        'report/room_booking_reports.xml',
        'report/sale_order_reports.xml',
        'report/advance_payment_receipt_report.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'kx_hotel_management/static/src/js/action_manager.js',
            'kx_hotel_management/static/src/css/dashboard.css',
            'kx_hotel_management/static/src/js/dashboard_action.js',
            'kx_hotel_management/static/src/xml/dashboard_templates.xml',
        ],
    },
    'images': ['static/description/banner.jpg'],
    # 'price': 50,
    # 'currency': 'USD',
    'license': 'LGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,
}
