from . import account_move
from . import account_move_line
from . import event_booking_line
from . import fleet_booking_line
from . import fleet_vehicle_model
from . import food_booking_line
from . import hotel_amenity
from . import hotel_floor
from . import hotel_room
from . import hotel_service
from . import room_booking
from . import room_booking_line
from . import service_booking_line
from . import customer_document
from . import hotel_room_image
